description: Pipeline to parse deployment github wehhooks
processors:
- set:
    field: observer.name
    value: '{{github.repository.name}}'
- set:
    field: observer.product
    value: Webhook
- set:
    field: observer.vendor
    value: Github
- append:
    field: related.user
    value: '{{github.sender.login}}'
    if: ctx.github?.sender?.type == 'User'
- append:
    field: related.user
    value: '{{github.deployment.creator.login}}'
    if: ctx.github?.deployment?.creator?.type == 'User' && !(ctx.related.user).contains(ctx.github.deployment.creator.login)
- append:
    field: event.type
    value:
    - info
    - creation
    - start
- set:
    field: event.kind
    value: event
- set:
    field: event.action
    value: deployment-{{github.action}}
- rename:
    field: github.deployment.id
    target_field: event.id
    ignore_missing: true
- rename:
    field: github.deployment.url
    target_field: event.url
    ignore_missing: true
- rename:
    field: github.sender.login
    target_field: source.user.name
    ignore_missing: true
- rename:
    field: github.sender.id
    target_field: source.user.id
    ignore_missing: true
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'
