description: Pipeline to parse deployment_status github wehhooks
processors:
- append:
    field: event.type
    value:
    - info
- append:
    field: event.type
    value:
    - end
    - creation
    if: ctx.github?.deployment_status?.state != 'pending'
- set:
    field: event.outcome
    value: success
    if: ctx.github?.deployment_status?.state == success
- set:
    field: event.outcome
    value: failure
    if: "['failure', 'error'].contains(ctx.github?.deployment_status?.state)"
- set:
    field: event.kind
    value: event
- set:
    field: event.action
    value: deployment_status-{{github.action}}
- rename:
    field: github.deployment.id
    target_field: github.related.deployment.id
    ignore_missing: true
- rename:
    field: github.deployment.url
    target_field: github.related.deployment.url
    ignore_missing: true
- rename:
    field: github.deployment.sha
    target_field: github.related.deployment.sha
    ignore_missing: true
- rename:
    field: github.deployment.task
    target_field: github.related.deployment.task
    ignore_missing: true
- remove:
    field:
    - github.check_run
    - github.check_suite
    - github.repository
    - github.organization
    - github.installation
    - github.deployment
    - github.deployment_status.creator
    - github.sender
    ignore_missing: true
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'
