description: Pipeline to parse deployment github wehhooks
processors:
- append:
    field: event.type
    value:
    - info
    - creation
- set:
    field: event.kind
    value: event
- set:
    field: event.action
    value: deployment-{{github.action}}
- rename:
    field: github.deployment.id
    target_field: github.related.deployment.id
    ignore_missing: true
- rename:
    field: github.deployment.url
    target_field: github.related.deployment.url
    ignore_missing: true
- rename:
    field: github.deployment.sha
    target_field: github.related.deployment.sha
    ignore_missing: true
- rename:
    field: github.deployment.task
    target_field: github.related.deployment.task
    ignore_missing: true
- remove:
    field:
    - github.deployment
    - github.repository
    - github.organization
    - github.installation
    - github.sender
    ignore_missing: true
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'
