description: Pipeline to parse package github wehhooks
processors:
- append:
    field: event.type
    value: installation
- append:
    field: event.type
    value: creation
    if: ctx.github?.action == 'published'
- append:
    field: event.type
    value: change
    if: ctx.github?.action == 'updated'
- set:
    field: event.action
    value: organization-{{github.action}}
- rename:
    field: github.package
    target_field: _temp_.package
    ignore_missing: true
- rename:
    field: _temp_.package.id
    target_field: github.package.id
    ignore_missing: true
- rename:
    field: _temp_.package.name
    target_field: github.package.name
    ignore_missing: true
- rename:
    field: _temp_.package.type
    target_field: github.package.type
    ignore_missing: true
- rename:
    field: _temp_.package.html_url
    target_field: github.package.url
    ignore_missing: true
- rename:
    field: _temp_.package.owner.login
    target_field: github.related.user.name
    ignore_missing: true
- rename:
    field: _temp_.package.owner.id
    target_field: github.related.user.id
    ignore_missing: true
- rename:
    field: _temp_.package.package_version.version
    target_field: github.package.version
    ignore_missing: true
- rename:
    field: _temp_.package.package_version.release.html_url
    target_field: github.package.release_url
    ignore_missing: true
- rename:
    field: _temp_.package.package_version.release.tag_name
    target_field: github.package.release_tag
    ignore_missing: true
- rename:
    field: _temp_.package.package_version.tag_name
    target_field: github.package.tag
    ignore_missing: true
- rename:
    field: _temp_.package.package_version.installation_command
    target_field: github.package.installation_command
    ignore_missing: true
- rename:
    field: _temp_.package.registry.name
    target_field: github.package.registry.name
    ignore_missing: true
- rename:
    field: _temp_.package.registry.type
    target_field: github.package.registry.type
    ignore_missing: true
- rename:
    field: _temp_.package.registry.vendor
    target_field: github.package.registry.vendor
    ignore_missing: true
- remove:
    field:
    - github.check_run
    - github.check_suite
    - github.repository
    - github.organization
    - github.installation
    - github.sender
    - _temp_
    ignore_missing: true
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'
