description: initial pipeline for all github wehhooks
processors:
- set:
    field: observer.name
    value: '{{github.repository.name}}'
- set:
    field: observer.product
    value: Webhook
- set:
    field: observer.vendor
    value: Github
- set:
    field: event.kind
    value: event
- append:
    field: event.category
    value: web
- rename:
    field: github.organization.login
    target_field: github.related.organization.name
    ignore_missing: true
- append:
    field: related.user
    value: "{{github.sender.login}}"
    if: ctx.github?.sender?.type == 'User'
- rename:
    field: github.repository.full_name
    target_field: github.related.repository.name
    ignore_missing: true
- rename:
    field: github.repository.id
    target_field: github.related.repository.id
    ignore_missing: true
- rename:
    field: github.repository.html_url
    target_field: github.related.repository.url
    ignore_missing: true
- rename:
    field: github.repository.private
    target_field: github.related.repository.private
    ignore_missing: true
- rename:
    field: github.sender.login
    target_field: source.user.name
    ignore_missing: true
- rename:
    field: github.sender.id
    target_field: source.user.id
    ignore_missing: true
- pipeline:
    name: '{< IngestPipeline "checks" >}'
    if: ctx.github?.checks_run != null || ctx.github?.checks_suite != null
- pipeline:
    name: '{< IngestPipeline "comment" >}'
    if: ctx.github?.comment != null

on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'