description: Pipeline to parse check_run and check_suite github wehhooks
processors:
- set:
    field: observer.name
    value: '{{github.repository.name}}'
- set:
    field: observer.product
    value: Webhook
- set:
    field: observer.vendor
    value: Github
- rename:
    field: github.organization.login
    target_field: github.related.organization
    ignore_missing: true
- append:
    field: related.user
    value: "{{github.sender.login}}"
    if: ctx.github?.sender?.type == 'User'
- pipeline:
    name: '{< IngestPipeline "checks" >}'
    if: ctx.github?.checks_run != null || ctx.github?.checks_suite != null
- pipeline:
    name: '{< IngestPipeline "comment" >}'
    if: ctx.github?.comment != null

on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'