description: Pipeline for normalizing Zeek dhcp.log
processors:
- set:
    field: event.created
    value: '{{_ingest.timestamp}}'
    ignore_empty_value: true
- date:
    field: zeek.dhcp.ts
    formats:
    - UNIX
- remove:
    field: zeek.dhcp.ts
- set:
    field: event.id
    value: '{{zeek.session_id}}'
    ignore_empty_value: true
- append:
    field: related.ip
    value: '{{source.ip}}'
    if: 'ctx?.source?.ip != null'
- append:
    field: related.ip
    value: '{{destination.ip}}'
    if: 'ctx?.destination?.ip != null'
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'
