// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package paloalto

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "paloalto", asset.ModuleFieldsPri, AssetPaloalto); err != nil {
		panic(err)
	}
}

// AssetPaloalto returns asset data.
// This is the base64 encoded gzipped contents of module/paloalto.
func AssetPaloalto() string {
	return "eJy0mM1u5DYMx+95Cr3AXgpsD3MoUKDouWgvvQkaibbZSKJXomYyb1/I85GM48lGtDOXAI7/P5EUSVH+pp7htFOj8WQ805NSjOzh7omDbBOOjBR36rcnpZT6hwLcXlGBXPHwpFSH4F3eTa/U3zcVTYCdenHp9kwpPo2wU32iMr55urDK9ffnhFUdJfWX8aR+r4v++8ffb16ar/y6NrwwpGi8RncHPVvxDKcjJbegC4btgLHXmQ2X3KSF6PSk14YZwsialwDOMCyoPdlqbsyQ2oR7JKsxOrSGKQm9hXRACzoVD60huzprqUSGJQM8xf6R4dYw9JROGmIJ+hlOTWtj1scBGTxmhiWz90QeTFyQZjYpNWocuDL6GmjQTM8Q2xKkQ8+QREEOyAk0gx0i/ihVrk10uv5TwjGW0YohpofI+gApI0WB0hk22pL3YGvhS2rN+FomjUG85lqTKFNJtjE+Z7fGBMxti8EB4mLtz/vmh53zU71zqXvONwpjZuO9rjbMVnjkyRwxUGa9J2LNGNohU0B0LnuZDeczap4nn7I+Z7JoLvmZIPY8NENcZr0JKHNtkQI3zvETC2Ubb5mSHhNZyFln7KPhkmCpzNtx1pRsPLIoGmfUKsSr+N4uDKaH9610DdJSCLU/e4zbQc92jkaQhI+Qrzt8gOhmI8g2YGHqzMFfsvPwArZM5S3qcB9vVHDfNybmwfzy/VdJ6VQXO/Sgg7GJVoIu4+64Tj9SYikhQSCGFSZcAGtsuF1T6jEpah4X0DR8zyabBvktReqBH63sxLxHrW3Ud2bJm+siaV3q3rNWdekZcYuzcpkn7MyULz0Euq4O6wfQJdeMFezEjbVFsr2Hyc+1B6xtnFyVHu9oqxPkA+LaFNmkxN7Hb00budG2oVxtoqzHNRweEhh3/SMgdUdtxlGodDB96hGld3fUJXntKBiMEjUEg77e5/4D235qvgIgOmjP1Zs+gcURIYpMqKHPZb/4NaEBsVY/fQwiT72IcMin9u7RHfVL10lkAbOV6DDrccA84N0XxM/Jp9t3L7z/VvEXTfwuZv2jQDrJanBya6vx8Q1MOkIu2SOaiS1FNhiz7mA6kdzk1gaYOrJsgPnJTeH/AAAA//9D6A9s"
}
