- module: carbonblack
  auditlog:
    enabled: true

    # Set which input to use, currently supports httpjson
    #var.input: httpjson

    # The interface to listen to UDP based syslog traffic. Defaults to
    # localhost. Set to 0.0.0.0 to bind to all available interfaces.
    #var.url: https://api-url.conferdeploy.net/integrationServices/v3/auditlogs

    # The UDP port to listen for syslog traffic. Defaults to 9001.
    #var.token: Username/Password
