description: Pipeline for parsing Abuse.ch Malware Threat Intel
processors:
- set:
    field: event.ingested
    value: '{{_ingest.timestamp}}'
- remove:
    field:
    - "@timestamp"
    ignore_missing: true
    if: ctx?.json?.firstseen != null
- date:
    field: json.firstseen
    formats:
      - "yyyy-MM-dd HH:mm:ss z"
      - "yyyy-MM-dd HH:mm:ss Z"
      - "yyyy-MM-dd HH:mm:ss"
    if: "ctx?.json?.firstseen != null"
- rename:
    field: json.file_size
    target_field: file.size
    ignore_missing: true
- rename:
    field: json.md5_hash
    target_field: file.hash.md5
    ignore_missing: true
- rename:
    field: json.sha256_hash
    target_field: file.hash.sha256
    ignore_missing: true
- rename:
    field: json
    target_field: threatintel
    ignore_missing: true
- append:
    field: related.hash
    value: '{{file.hash.md5}}'
    if: ctx?.file?.hash?.md5 != null
- append:
    field: related.hash
    value: '{{file.hash.sha256}}'
    if: ctx?.file?.hash?.sha256 != null
- remove:
    field: threatintel.virustotal
    ignore_missing: true
    if: ctx?.threatintel?.virustotal == null
- remove:
    field:
    - threatintel.firstseen
    - message
    ignore_missing: true
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'
