description: Pipeline for parsing checkpoint firewall logs
processors:
- set:
    field: event.ingested
    value: '{{_ingest.timestamp}}'
- json:
    field: message
    target_field: json
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'
