{{ if eq .input "httpjson" }}

type: httpjson
http_method: GET
http_headers: {"Content-Type": "application/json"}
interval: {{ .interval }}
json_objects_array: response
split_events_by: Event..Attribute
url: {{ .url }}

{{ else if eq .input "file" }}

type: log
paths:
{{ range $i, $path := .paths }}
  - {{$path}}
{{ end }}
exclude_files: [".gz$"]

{{ end }}

tags: {{.tags | tojson}}
publisher_pipeline.disable_host: {{ inList .tags "forwarded" }}

processors:
  - decode_json_fields:
      fields: [message]
      target: json
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.6.0
