{{ if eq .input "httpjson" }}

type: httpjson
config_version: "2"
interval: {{ .interval }}

auth.basic.user: {{ .client_id }}
auth.basic.password: {{ .api_key }}

request.url: {{ .url }}
request.method: GET
request.timeout: 50s
request.ssl: {{ .ssl | tojson }}
request.transforms:
- set: {{ .start_date | tojson }}
request.rate_limit.limit: {{ .rate_limit | tojson}}
request.rate_limit.reset: {{ .rate_reset | tojson}}
request.rate_limit.remaining: {{ .rate_remaining | tojson}}

response.pagination:
- set: {{ .link_pagination | tojson }}

response.split:
  target: body.data
  keep_parent: true

{{ else if eq .input "file" }}

type: log
paths:
{{ range $i, $path := .paths }}
  - {{$path}}
{{ end }}
exclude_files: [".gz$"]

{{ end }}


tags: {{.tags | tojson}}
publisher_pipeline.disable_host: {{ inList .tags "forwarded" }}

processors:
  - decode_json_fields:
      fields: [message]
      target: json
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.6.0
