{{ if eq .input "httpjson" }}

type: httpjson
http_method: GET
interval: {{ .interval }}
json_objects_array: notifications
url: {{ .url }}

http_headers:
  User-Agent: MdatpPartner-Elastic-Filebeat/1.0.0

{{ else if eq .input "file" }}

type: log
paths:
{{ range $i, $path := .paths }}
  - {{$path}}
{{ end }}
exclude_files: [".gz$"]

{{ end }}

tags: {{.tags | tojson}}
publisher_pipeline.disable_host: {{ inList .tags "forwarded" }}

processors:
  - decode_json_fields:
      fields: [message]
      target: json
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.6.0
