description: Pipeline for parsing checkpoint firewall logs
processors:

- remove:
    field:
    - message
    - version
    - metadata
    ignore_missing: true
#########################
## ECS General Mapping ##
#########################
- set:
    field: event.ingested
    value: '{{_ingest.timestamp}}'
- rename:
    field: json
    target_field: cisco.amp
    ignore_missing: true
- remove:
    field:
    - "@timestamp"
    ignore_missing: true
    if: ctx?.cisco?.amp?.timestamp != null
- date:
    field: cisco.amp.timestamp
    formats:
      - UNIX
    ignore_failure: true

#######################
## ECS Event Mapping ##
#######################
- rename:
    field: cisco.amp.id
    target_field: event.id
    ignore_missing: true
- rename:
    field: cisco.amp.event_type
    target_field: event.action
    ignore_missing: true
- rename:
    field: cisco.amp.severity
    target_field: event.severity
    ignore_missing: true

######################
## ECS Host Mapping ##
######################
- rename:
    field: cisco.amp.computer.hostname
    target_field: host.name
    ignore_missing: true
- set:
    field: host.hostname
    value: "{{ host.name }}"
    if: ctx?.host?.name != null
- rename:
    field: cisco.amp.computer.user
    target_field: host.user.name
    ignore_missing: true

#########################
## ECS Network Mapping ##
#########################
- rename:
    field: cisco.amp.network_info.nfm.protocol
    target_field: network.transport
    ignore_missing: true
- set:
    field: network.direction
    value: outbound
    if: "ctx?.cisco?.amp?.network_info?.nfm?.direction == 'Outgoing connection from'"
- set:
    field: network.direction
    value: outbound
    if: "ctx?.cisco?.amp?.network_info?.nfm?.direction != null && ctx?.cisco?.amp?.network_info?.nfm?.direction != 'Outgoing connection from'"

#####################
## ECS URL Mapping ##
#####################
- rename:
    field: cisco.amp.network_info.dirty_url
    target_field: url.full
    ignore_missing: true

########################
## ECS Source Mapping ##
########################
- rename:
    field: cisco.amp.network_info.local_ip
    target_field: source.address
    ignore_missing: true
- rename:
    field: cisco.amp.network_info.local_port
    target_field: source.port
    ignore_missing: true
- set:
    field: source.ip
    value: "{{ source.address }}"
    if: ctx?.source?.address != null

#############################
## ECS Destination Mapping ##
#############################
- rename:
    field: cisco.amp.network_info.remote_ip
    target_field: destination.address
    ignore_missing: true
- rename:
    field: cisco.amp.network_info.remote_port
    target_field: destination.port
    ignore_missing: true
- set:
    field: destination.ip
    value: "{{ destination.address }}"
    if: ctx?.destination?.address != null

######################
## ECS File Mapping ##
######################
- rename:
    field: cisco.amp.file.file_name
    target_field: file.name
    ignore_missing: true
- rename:
    field: cisco.amp.file.file_path
    target_field: file.path
    ignore_missing: true
- rename:
    field: cisco.amp.file.identity.sha256
    target_field: file.hash.sha256
    ignore_missing: true
- rename:
    field: cisco.amp.file.identity.sha1
    target_field: file.hash.sha1
    ignore_missing: true
- rename:
    field: cisco.amp.file.identity.md5
    target_field: file.hash.md5
    ignore_missing: true

#########################
## ECS Process Mapping ##
#########################
- rename:
    field: cisco.amp.file.parent.process_id
    target_field: process.parent.pid
    ignore_missing: true
- rename:
    field: cisco.amp.file.parent.file_name
    target_field: process.parent.name
    ignore_missing: true
- rename:
    field: cisco.amp.file.parent.identity.sha256
    target_field: process.parent.hash.sha256
    ignore_missing: true
- rename:
    field: cisco.amp.file.parent.identity.sha1
    target_field: process.parent.hash.sha1
    ignore_missing: true
- rename:
    field: cisco.amp.file.parent.identity.md5
    target_field: process.parent.hash.md5
    ignore_missing: true

- rename:
    field: cisco.amp.network_info.parent.process_id
    target_field: process.parent.pid
    ignore_missing: true
- rename:
    field: cisco.amp.network_info.parent.file_name
    target_field: process.parent.name
    ignore_missing: true
- rename:
    field: cisco.amp.network_info.parent.identity.sha256
    target_field: process.parent.hash.sha256
    ignore_missing: true
- rename:
    field: cisco.amp.network_info.parent.identity.sha1
    target_field: process.parent.hash.sha1
    ignore_missing: true
- rename:
    field: cisco.amp.network_info.parent.identity.md5
    target_field: process.parent.hash.md5
    ignore_missing: true

#########################
## ECS Related Mapping ##
#########################
- append:
    field: related.user
    value: "{{ host.user.name }}"
    if: ctx?.host?.user?.name != null
- append:
    field: related.hash
    value: "{{ process.parent.hash.sha256 }}"
    if: ctx?.process?.parent?.hash?.sha256 != null
- append:
    field: related.hash
    value: "{{ process.parent.hash.md5 }}"
    if: ctx?.process?.parent?.hash?.md5 != null
- append:
    field: related.hash
    value: "{{ process.parent.hash.sha1 }}"
    if: ctx?.process?.parent?.hash?.sha1 != null
- append:
    field: related.hash
    value: "{{ file.hash.sha256 }}"
    if: ctx?.file?.hash?.sha256 != null
- append:
    field: related.hash
    value: "{{ file.hash.md5 }}"
    if: ctx?.file?.hash?.md5 != null
- append:
    field: related.hash
    value: "{{ file.hash.sha1 }}"
    if: ctx?.file?.hash?.sha1 != null
- append:
    field: related.hash
    value: "{{ cisco.amp.network_info.parent.identity.sha256 }}"
    if: ctx?.cisco?.amp?.network_info?.parent?.identity?.sha256 != null
- append:
    field: related.hash
    value: "{{ cisco.amp.network_info.parent.identity.md5 }}"
    if: ctx?.cisco?.amp?.network_info?.parent?.identity?.md5 != null
- append:
    field: related.hash
    value: "{{ cisco.amp.network_info.parent.identity.sha1 }}"
    if: ctx?.cisco?.amp?.network_info?.parent?.identity?.sha1 != null
- foreach:
    field: cisco.amp.computer.network_addresses
    processor:
      append:
        field: related.ip
        value: "{{ _ingest._value.ip }}"
    if: ctx?.cisco?.amp?.computer?.network_addresses != null
- foreach:
    field: cisco.amp.computer.network_addresses
    processor:
      append:
        field: cisco.amp.related.mac
        value: "{{ _ingest._value.mac }}"
    if: ctx?.cisco?.amp?.computer?.network_addresses != null
- foreach:
    field: cisco.amp.vulnerabilities
    processor:
      append:
        field: cisco.amp.related.cve
        value: "{{ _ingest._value.cve }}"
    if: ctx?.cisco?.amp?.vulnerabilities != null

#############
## Cleanup ##
#############
- remove:
    field:
    - cisco.amp.timestamp
    - cisco.amp.computer.links
    ignore_missing: true
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'

