description: Pipeline for parsing checkpoint firewall logs
processors:
- set:
    field: event.ingested
    value: '{{_ingest.timestamp}}'
- remove:
    field:
    - message
    ignore_missing: true
- rename:
    field: json
    target_field: cisco.amp
    ignore_missing: true
- rename:
    field: cisco.amp.id
    target_field: event.id
    ignore_missing: true
- rename:
    field: cisco.amp.event_type
    target_field: event.action
    ignore_missing: true
- date:
    field: cisco.amp.timestamp
    formats:
      - UNIX
    ignore_failure: true
- rename:
    field: cisco.amp.id
    target_field: event.id
    ignore_missing: true
- rename:
    field: cisco.amp.computer.hostname
    target_field: host.name
    ignore_missing: true
- set:
    field: host.hostname
    value: "{{ host.name }}"
    if: ctx?.host?.name != null
- rename:
    field: cisco.amp.computer.external_ip
    target_field: destination.address
    ignore_missing: true
- set:
    field: destination.ip
    value: "{{ destination.address }}"
    if: ctx?.destination?.address != null
- rename:
    field: cisco.amp.computer.user
    target_field: host.user.name
    ignore_missing: true
- rename:
    field: cisco.amp.file.file_name
    target_field: file.name
    ignore_missing: true
- rename:
    field: cisco.amp.file.file_path
    target_field: file.path
    ignore_missing: true
- rename:
    field: cisco.amp.file.identity.sha256
    target_field: file.hash.sha256
    ignore_missing: true
- rename:
    field: cisco.amp.file.identity.sha1
    target_field: file.hash.sha1
    ignore_missing: true
- rename:
    field: cisco.amp.file.identity.md5
    target_field: file.hash.md5
    ignore_missing: true
- rename:
    field: cisco.amp.file.parent.process_id
    target_field: process.parent.pid
    ignore_missing: true
- rename:
    field: cisco.amp.file.parent.file_name
    target_field: process.parent.name
    ignore_missing: true
- rename:
    field: cisco.amp.file.parent.identity.sha256
    target_field: process.parent.hash.sha256
    ignore_missing: true
- rename:
    field: cisco.amp.file.parent.identity.sha1
    target_field: process.parent.hash.sha1
    ignore_missing: true
- rename:
    field: cisco.amp.file.parent.identity.md5
    target_field: process.parent.hash.md5
    ignore_missing: true
# Setting related fields
- append:
    field: related.user
    value: "{{ host.user.name }}"
    if: ctx?.host?.user?.name != null
- foreach:
    field: cisco.amp.computer.network_addresses
    processor:
      append:
        field: related.ip
        value: "{{ _ingest._value.ip }}"
    if: ctx?.cisco?.amp?.computer?.network_addresses != null
- foreach:
    field: cisco.amp.computer.network_addresses
    processor:
      append:
        field: cisco.amp.related.mac
        value: "{{ _ingest._value.mac }}"
    if: ctx?.cisco?.amp?.computer?.network_addresses != null
- remove:
    field:
    - cisco.amp.timestamp
    ignore_missing: true
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'

