---
description: Pipeline for parsing microsoft atp logs
processors:
- set:
    field: event.ingested
    value: '{{_ingest.timestamp}}'
- remove:
    field:
      - message
      - json.comments
      - host
    ignore_missing: true

#########################
## ECS General Mapping ##
#########################
- script:
    lang: painless
    if: ctx?.json != null
    params:
      values:
        - null
        - ""
        - "-"
        - "N/A"
    source: |
      if (!ctx['json'].empty) {
        ctx.json.entrySet().removeIf(entry -> params.values.contains(entry.getValue()));
      }
- script:
    lang: painless
    if: ctx?.json?.evidence != null
    params:
      values:
        - null
        - ""
        - "-"
        - "N/A"
    source: |
      if (!ctx.json['evidence'].empty) {
        ctx.json.evidence.entrySet().removeIf(entry -> params.values.contains(entry.getValue()));
      }
- set:
    field: cloud.provider
    value: azure
- set:
    field: '@timestamp'
    value: '{{json.lastUpdateTime}}'
    if: ctx.json?.lastUpdateTime != null

#######################
## ECS Event Mapping ##
#######################
- set:
    field: event.kind
    value: alert
# Events returned from the API is always in UTC, so should never use anything else
- set:
    field: event.timezone
    value: UTC
- set:
    field: event.action
    value: '{{json.alert.category}}'
    if: ctx.json?.alert?.category != null
- set:
    field: event.provider
    value: '{{json.alert.serviceSource}}'
    if: ctx.json?.alert?.serviceSource != null
- set:
    field: event.created
    value: '{{json.createdTime}}'
    if: ctx.json?.createdTime != null
- append:
    field: event.category
    value: host
- append:
    field: event.category
    value: malware
    if: ctx.json?.determination == 'Malware'
- append:
    field: event.category
    value: process
    if: ctx.json?.entities?.entityType == 'Process'
- append:
    field: event.type
    value: user
    if: ctx.json?.entities?.entityType == 'User'
- append:
    field: event.type
    value:
      - creation
      - start
    if: ctx.json?.status == 'New'
- append:
    field: event.type
    value: end
    if: ctx.json?.status == 'Resolved'
- rename:
    field: json.alert.alertId
    target_field: event.id
    ignore_missing: true
- rename:
    field: json.alert.firstActivity
    target_field: event.start
    ignore_missing: true
- rename:
    field: json.alert.lastActivity
    target_field: event.end
    ignore_missing: true
- set:
    field: event.severity
    value: 0
    if: ctx.json?.severity == 'Unspecified'
- set:
    field: event.severity
    value: 1
    if: ctx.json?.severity == 'Informational'
- set:
    field: event.severity
    value: 2
    if: ctx.json?.severity == 'Low'
- set:
    field: event.severity
    value: 3
    if: ctx.json?.severity == 'Medium'
- set:
    field: event.severity
    value: 4
    if: ctx.json?.severity == 'High'
- script:
    lang: painless
    if: "ctx?.event?.start != null && ctx?.event?.end != null"
    source: >
      Instant eventstart = ZonedDateTime.parse(ctx?.event?.start).toInstant();
      Instant eventend = ZonedDateTime.parse(ctx?.event?.end).toInstant();
      ctx.event['duration'] = ChronoUnit.NANOS.between(eventstart, eventend);

########################
## ECS Threat Mapping ##
########################
- set:
    field: threat.framework
    value: MITRE ATT&CK
    if: ctx.json?.alert.category != null
- rename:
    field: json.alert.category
    target_field: threat.technique.name
    ignore_missing: true
- rename:
    field: json.description
    target_field: rule.description
    ignore_missing: true
    if: (ctx.json?.description).length() < 1020

######################
## ECS File Mapping ##
######################
- rename:
    field: json.entities.fileName
    target_field: file.name
    ignore_missing: true
- rename:
    field: json.entities.sha256
    target_field: file.hash.sha256
    ignore_missing: true
- rename:
    field: json.entities.sha1
    target_field: file.hash.sha1
    ignore_missing: true
- rename:
    field: json.entities.filePath
    target_field: file.path
    ignore_missing: true

#########################
## ECS Process Mapping ##
#########################
- rename:
    field: json.entities.processId
    target_field: process.pid
    ignore_missing: true
- rename:
    field: json.entities.processCommandLine
    target_field: process.command_line
    ignore_missing: true
- rename:
    field: json.entities.processCreationTime
    target_field: process.start
    ignore_missing: true
- rename:
    field: json.entities.parentProcessId
    target_field: process.parent.pid
    ignore_missing: true
- rename:
    field: json.entities.parentProcessCreationTime
    target_field: process.parent.start
    ignore_missing: true

##########################
## ECS Observer Mapping ##
##########################
- set:
    field: observer.product
    value: 365 Defender
- set:
    field: observer.vendor
    value: Microsoft
- rename:
    field: json.serviceSource
    target_field: observer.name
    ignore_missing: true

#####################
## ECS URL Mapping ##
#####################
- rename:
    field: json.entities.url
    target_field: url.full
    ignore_missing: true
    if: ctx?.json?.entities?.url != null

######################
## ECS User Mapping ##
######################
- rename:
    field: json.entities.userPrincipalName
    target_field: host.user.name
    ignore_missing: true
    if: ctx?.entities.entityType == "User"
- rename:
    field: json.entities.domainName
    target_field: host.user.domain
    ignore_missing: true
    if: ctx?.entities.entityType == "User"
- rename:
    field: json.entities.userSid
    target_field: host.user.id
    ignore_missing: true
    if: ctx?.entities.entityType == "User"

#########################
## ECS Related Mapping ##
#########################
- append:
    field: related.ip
    value: '{{json.evidence.ipAddress}}'
    if: ctx.json?.evidence?.ipAddress != null
- append:
    field: related.user
    value: '{{host.user.name}}'
    if: ctx.host?.user?.name != null
- append:
    field: related.hash
    value: '{{file.hash.sha1}}'
    if: ctx.file?.hash?.sha1 != null
- append:
    field: related.hash
    value: '{{file.hash.sha256}}'
    if: ctx.file?.hash?.sha256 != null
- append:
    field: related.hosts
    value: '{{host.hostname}}'
    if: ctx.host?.hostname != null

#############
## Cleanup ##
#############
- rename:
    field: json
    target_field: microsoft.365_defender
    ignore_missing: true
on_failure:
- set:
    field: error.message
    value: '{{_ingest.on_failure_message}}'
