description: Pipeline for normalizing Zeek stats.log
processors:
- set:
    field: event.created
    value: '{{_ingest.timestamp}}'
    ignore_empty_value: true
- date:
    field: zeek.stats.ts
    formats:
    - UNIX
- remove:
    field: zeek.stats.ts
- set:
    field: event.kind
    value: metric
on_failure:
- set:
    field: error.message
    value: '{{ _ingest.on_failure_message }}'
