{{ if eq .input "httpjson" }}

type: httpjson
http_method: {{ .http_method }}
http_headers: {{ .http_headers }}
interval: {{ .interval }}
json_objects_array: {{ .json_objects_array }}
url: {{ .url }}
ssl: {{ .ssl }}

oauth2: {{ .oauth2 | tojson }}
oauth2.provider: azure
{{ else if eq .input "file" }}

type: log
paths:
{{ range $i, $path := .paths }}
  - {{$path}}
{{ end }}
exclude_files: [".gz$"]

{{ end }}

processors:
  - decode_json_fields:
      fields: [message]
      target: json
