{{ if eq .input "httpjson" }}

type: httpjson
http_method: GET
http_headers: {"Content-Type": "application/json"}
interval: {{ .interval }}
json_objects_array: value
url: {{ .url }}

oauth2: {{ .oauth2 | tojson }}
oauth2.provider: azure
oauth2.azure.resource: https://api.securitycenter.windows.com/

{{ else if eq .input "file" }}

type: log
paths:
{{ range $i, $path := .paths }}
  - {{$path}}
{{ end }}
exclude_files: [".gz$"]

{{ end }}

tags: {{.tags | tojson}}
publisher_pipeline.disable_host: {{ inList .tags "forwarded" }}

processors:
  - decode_json_fields:
      fields: [message]
      target: json
