{{ if eq .input "httpjson" }}

type: httpjson
http_method: GET
http_headers: {"Content-Type": "application/json"}
interval: {{ .interval }}
json_objects_array: value
split_events_by: evidence
url: {{ .url }}
date_cursor.value_template: {{ .date_cursor.value_template }}

date_cursor.field: "alertCreationTime"
date_cursor.url_field: '$filter'

date_cursor.initial_interval: 10m
date_cursor.date_format: '2006-01-02T15:04:05.9999999Z'

oauth2: {{ .oauth2 | tojson }}
oauth2.azure.resource: https://api.securitycenter.windows.com/

{{ else if eq .input "file" }}

type: log
paths:
{{ range $i, $path := .paths }}
  - {{$path}}
{{ end }}
exclude_files: [".gz$"]

{{ end }}

tags: {{.tags | tojson}}
publisher_pipeline.disable_host: {{ inList .tags "forwarded" }}

processors:
  - decode_json_fields:
      fields: [message]
      target: json
